version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Publish tool docker locally
          working_directory: ~/workdir
          command: ./build.sh
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag codacy/${CIRCLE_PROJECT_REPONAME}:latest codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build